using HatzeLaboratory.GameBasicSystem.Runtime.System;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace HatzeLaboratory.GameBasicSystem.Editor.Creation.EnumCreator.Core
{
    public class EnumCreatorBase
    {
        /// <returns>
        /// <para>true: ファイルの作成に成功</para>
        /// <para>false: ファイルの作成に失敗</para>
        /// </returns>
        internal bool CreateEnum()
        {
            try
            {
                List<string> lineTextList = GetWriteTextList();
                string filePath = GetFilePath();
                string fileDirectory = Path.GetDirectoryName(filePath);
                if (!Directory.Exists(fileDirectory))
                {
                    Directory.CreateDirectory(fileDirectory);
                }

                using (FileStream fileStream = new(filePath, FileMode.Create))
                using (StreamWriter streamWriter = new(fileStream, Encoding.UTF8))
                {
                    foreach (string codeString in lineTextList)
                    {
                        streamWriter.WriteLine(codeString);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"{e.Message}\n{e.StackTrace}");
                return false;
            }

            AssetDatabase.Refresh();
            return true;
        }

        internal bool HasPendingChanges()
        {
            string filePath = GetFilePath();
            if (!File.Exists(filePath))
            {
                return true;
            }

            try
            {
                string existingContent = File.ReadAllText(filePath, Encoding.UTF8);
                StringBuilder stringBuilder = new();
                foreach (string line in GetWriteTextList())
                {
                    stringBuilder.AppendLine(line);
                }

                return Normalize(existingContent) != Normalize(stringBuilder.ToString());
            }
            catch
            {
                return true;
            }
        }

        internal bool IsEnumExisted()
        {
            string filePath = GetFilePath();
            return File.Exists(filePath);
        }

        protected virtual void WriteData(List<string> outputStringList)
        {

        }

        protected virtual string GetFileName()
        {
            return string.Empty;
        }

        protected virtual string GetFileRootPath()
        {
            return string.Empty;
        }

        protected virtual string GetFilePath()
        {
            return Path.Combine(Application.dataPath, GetFileRootPath(), GetFileName());
        }

        protected virtual string GetCreatorFileName()
        {
            return string.Empty;
        }

        protected virtual string GetNameSpace()
        {
            return string.Empty;
        }

        protected virtual string GetEnumName()
        {
            return string.Empty;
        }

        private List<string> GetWriteTextList()
        {
            List<string> lineList = new();
            lineList.Add($"// Auto-generated by {GetCreatorFileName()}.cs");
            lineList.Add($"namespace {GetNameSpace()}");
            lineList.Add("{");
            lineList.Add($"\tpublic enum {GetEnumName()}");
            lineList.Add("\t{");
            WriteData(lineList);
            lineList.Add("\t}");
            lineList.Add("}");

            return lineList;
        }

        private string Normalize(string text)
        {
            return string.Concat(text.Where(c => !char.IsWhiteSpace(c)));
        }
    }
}
